#%RAML 1.0
baseUri: https://localhost:8081/api
title: deltaflights
/deltaFlightsByDestination:
  get:
    queryParameters: 
      destination:
    responses: 
      200: 
        body:    
          application/json: 
          
           

      
/listAllDeltaFlights:
  get: 
    responses: 
      200: 
        body: 
          application/json: 
            
                                        